version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
